sudo: true
language: node_js
node_js: '9'
notifications:
  email: false
  slack:
    rooms:
      - secure: UxXFX+TCULNOrjtxazTFSWFHyVtwCpEfTzWVFIWXWf5Kot98h0epVSDqscrx2sC9UFRNBBweUIyk9M4VkgYgy2JjyE64OswJAw+qSpBm//k90PM8RygFw1IX3sKzoChgrnPKQh6W/2bqjPnQWdZC8HMsqWq5J3vMMdY30r4BifbLweQmUImQbMjXwY+PNVToD9aXMmeTNt/Xm4W7sFD4Nwg4bTDZF/hFC+VjhV4gCYthGeNjFchqnzGRNu/u2RFdkKyBOM2yEtHXvWMjBJJHyouUGRAJJhVQzGulKFgIMGewT01yCQoX9/b6GdtMLvBd53BGAyXGrq7LQqFiE/n1BU1QQtemWQDJuhtN1lBCFGfYa7NJ9nYq12xgrTHSErCakun+THphFGVBuheFAR0lXqj1VjkESf+4wzCUmWx1sV+/Qrk9n+cyg+/yEN2Cvq39mWS43ae0VAC28OYSEtsY1PTKS02sxJ33n40tiohvPnlMyxhyDdjnx9EvQYEgnsDUKmy/6rEbrNX4ZX1YwUPEYe3uK/OE+JpjZRr+I8qPpJgx7NwSpKCHQ7My1KEwAs8t2vj+ZaIPweAaUyKcz24D6H4LrBQXo0jQpjp0JcdxdpoXXTIjrXbUr8oDXBoli5e8SLmrVDjGqjGXADO1jkH3hUOHboXWAYFYymT1l+L2v1Q=
    on_success: always
    on_failure: always
    template:
      - Repo `%{repository_slug}` *%{result}* build (<%{build_url}|#%{build_number}>)
        for commit (<%{compare_url}|%{commit}>) on branch `%{branch}`.
      - 'Execution time: *%{duration}*'
      - 'Message: %{message}'
stages:
- name: build
  if: type = pull_request
- name: dev_deploy
  if: branch = develop AND type = push
- name: prod_deploy
  if: branch = release AND type = push
- name: release
  if: branch = master and type = push
jobs:
  include:
  - stage: build
  - stage: dev_deploy
    before_install:
    - sudo apt-get install sshpass
    script:
    - sshpass -p $DEV_MACHINE_PASSWORD ssh -o StrictHostKeyChecking=no $DEV_MACHINE_USERNAME@$DEV_MACHINE_IP
      "cd /FogController; NODE_ENV=production node src/main.js stop; git pull; npm
      i; NODE_ENV=production node src/main.js start"
  - stage: prod_deploy
    before_install:
    - sudo apt-get install sshpass
    script:
    - sshpass -p $PROD_MACHINE_PASSWORD ssh -o StrictHostKeyChecking=no $PROD_MACHINE_USERNAME@$PROD_MACHINE_IP
      "cd /Controller; NODE_ENV=production node src/main.js stop; git pull; npm i;
      NODE_ENV=production node src/main.js start"
  - stage: release
    deploy:
      skip_cleanup: true
      provider: npm
      email: "${NPM_EMAIL_ADDRESS}"
      api_key: "${NPM_AUTH_TOKEN}"
      on:
        tags: false
